server {
    listen 80;
    listen [::]:80;
    server_name masyralabs.com www.masyralabs.com;

    root /var/www/masyra-labs;
    index index.html;

    access_log /var/log/nginx/masyralabs.com.access.log;
    error_log /var/log/nginx/masyralabs.com.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
