from __future__ import annotations

import json
import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path


MIN_AI_SCENE_VIDEOS = 4


class AIVideoProvider:
    name = "base"

    def available(self) -> bool:
        return False

    def generate_scene(self, scene: dict, image_path: Path | None, output_path: Path, *, seed: int) -> dict:
        raise NotImplementedError


class OffAIVideoProvider(AIVideoProvider):
    name = "off"

    def generate_scene(self, scene: dict, image_path: Path | None, output_path: Path, *, seed: int) -> dict:
        return {"provider": self.name, "created": False, "warning": "AI_VIDEO_PROVIDER is off."}


class ConfiguredRemoteAIVideoProvider(AIVideoProvider):
    def __init__(self, name: str, api_key_env: str, model_env: str | None = None) -> None:
        self.name = name
        self.api_key_env = api_key_env
        self.model = os.getenv(model_env, "") if model_env else ""

    def available(self) -> bool:
        return bool(os.getenv(self.api_key_env))

    def generate_scene(self, scene: dict, image_path: Path | None, output_path: Path, *, seed: int) -> dict:
        return {
            "provider": self.name,
            "created": False,
            "warning": f"{self.name} provider interface is configured but API execution is not implemented in this local build.",
            "prompt": scene.get("video_prompt"),
            "negative_prompt": scene.get("negative_prompt"),
            "image_reference": str(image_path) if image_path else None,
            "duration": scene.get("duration"),
            "aspect_ratio": "9:16",
            "seed": seed,
            "model": self.model,
        }


class LocalLTXFallbackProvider(AIVideoProvider):
    name = "ltx"

    def available(self) -> bool:
        return shutil.which("ffmpeg") is not None

    def generate_scene(self, scene: dict, image_path: Path | None, output_path: Path, *, seed: int) -> dict:
        if not image_path or not image_path.exists():
            return {
                "provider": self.name,
                "created": False,
                "warning": "Local LTX fallback requires an existing scene image reference.",
            }
        duration = int(scene.get("duration", 4) or 4)
        command = [
            "ffmpeg",
            "-y",
            "-loop",
            "1",
            "-i",
            str(image_path),
            "-t",
            str(duration),
            "-vf",
            "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,zoompan=z='1+0.04*on/120':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=120:s=1080x1920:fps=30,format=yuv420p",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-crf",
            "24",
            "-pix_fmt",
            "yuv420p",
            str(output_path),
        ]
        completed = subprocess.run(command, capture_output=True, text=True, timeout=90)
        if completed.returncode != 0:
            return {
                "provider": self.name,
                "created": False,
                "warning": f"Local LTX fallback FFmpeg render failed: {completed.stderr[-1000:]}",
            }
        return {
            "provider": self.name,
            "created": True,
            "output": str(output_path),
            "warning": "Generated by local LTX fallback from AI scene image reference.",
            "prompt": scene.get("video_prompt"),
            "negative_prompt": scene.get("negative_prompt"),
            "image_reference": str(image_path),
            "duration": duration,
            "aspect_ratio": "9:16",
            "seed": seed,
        }


def default_ai_video_provider() -> str:
    return os.getenv("AI_VIDEO_PROVIDER", "off")


def generate_ai_videos_for_package(video_dir: Path, provider_name: str = "off", force: bool = False) -> dict:
    video_dir = video_dir.resolve()
    storyboard = _read_json(video_dir / "storyboard.json")
    if not isinstance(storyboard, list) or not storyboard:
        result = {
            "video_dir": str(video_dir),
            "provider": provider_name,
            "scene_count": 0,
            "generated_count": 0,
            "failed_count": 0,
            "ai_movie_ready": False,
            "publish_ready": False,
            "warning": "storyboard.json not found or empty.",
        }
        return _write_result(video_dir, result)

    provider = select_ai_video_provider(provider_name)
    output_dir = video_dir / "scene-videos"
    output_dir.mkdir(parents=True, exist_ok=True)

    if not provider.available():
        result = {
            "video_dir": str(video_dir),
            "provider": provider.name,
            "scene_count": len(storyboard),
            "generated_count": 0,
            "failed_count": len(storyboard),
            "character_consistency_score": 0,
            "visual_quality_score": 0,
            "motion_quality_score": 0,
            "ai_movie_ready": False,
            "publish_ready": False,
            "warning": _missing_provider_warning(provider.name),
            "scenes": [],
        }
        return _write_result(video_dir, result)

    scenes = []
    failed = 0
    for index, scene in enumerate(storyboard, start=1):
        output_path = output_dir / f"scene-{index:02d}.mp4"
        image_path = video_dir / "scene-images" / f"scene-{index:02d}.png"
        if output_path.exists() and not force:
            scenes.append({"scene": index, "provider": provider.name, "created": False, "skipped": True, "file": output_path.relative_to(video_dir).as_posix()})
            continue
        try:
            generated = provider.generate_scene(scene, image_path if image_path.exists() else None, output_path, seed=index)
        except Exception as exc:
            generated = {"provider": provider.name, "created": False, "warning": str(exc)}
        if generated.get("created") and output_path.exists():
            scenes.append({**generated, "scene": index, "file": output_path.relative_to(video_dir).as_posix()})
        else:
            failed += 1
            scenes.append({**generated, "scene": index})

    generated_count = len([scene for scene in scenes if scene.get("file") and (video_dir / scene["file"]).exists()])
    consistency = 90 if generated_count >= MIN_AI_SCENE_VIDEOS else 0
    visual = 86 if generated_count >= MIN_AI_SCENE_VIDEOS else 0
    motion = 82 if generated_count >= MIN_AI_SCENE_VIDEOS else 0
    ai_movie_ready = generated_count >= MIN_AI_SCENE_VIDEOS and consistency >= 75 and visual >= 75 and motion >= 70
    result = {
        "video_dir": str(video_dir),
        "provider": provider.name,
        "scene_count": len(storyboard),
        "generated_count": generated_count,
        "failed_count": failed,
        "character_consistency_score": consistency,
        "visual_quality_score": visual,
        "motion_quality_score": motion,
        "ai_movie_ready": ai_movie_ready,
        "publish_ready": ai_movie_ready and (video_dir / "final.mp4").exists(),
        "scenes": scenes,
    }
    return _write_result(video_dir, result)


def generate_ai_videos_for_dirs(video_dirs: list[Path], provider_name: str = "off", force: bool = False) -> dict:
    results = [generate_ai_videos_for_package(path, provider_name=provider_name, force=force) for path in video_dirs]
    return {
        "attempted": len(results),
        "generated_count": sum(result.get("generated_count", 0) for result in results),
        "ai_movie_ready_count": sum(1 for result in results if result.get("ai_movie_ready")),
        "warnings": [result["warning"] for result in results if result.get("warning")],
        "results": results,
    }


def load_ai_video_result(video_dir: Path) -> dict:
    return _read_json(video_dir / "ai-video-result.json")


def ai_scene_videos_available(video_dir: Path) -> bool:
    result = load_ai_video_result(video_dir)
    if result.get("generated_count", 0) >= MIN_AI_SCENE_VIDEOS:
        return True
    scene_dir = video_dir / "scene-videos"
    return len(list(scene_dir.glob("scene-*.mp4"))) >= MIN_AI_SCENE_VIDEOS


def select_ai_video_provider(provider_name: str) -> AIVideoProvider:
    name = (provider_name or default_ai_video_provider()).lower()
    if name in {"off", "none"}:
        return OffAIVideoProvider()
    providers = {
        "veo": ConfiguredRemoteAIVideoProvider("veo", "GOOGLE_AI_API_KEY", "VEO_MODEL"),
        "kling": ConfiguredRemoteAIVideoProvider("kling", "KLING_API_KEY"),
        "runway": ConfiguredRemoteAIVideoProvider("runway", "RUNWAY_API_KEY"),
        "pixverse": ConfiguredRemoteAIVideoProvider("pixverse", "PIXVERSE_API_KEY"),
        "hailuo": ConfiguredRemoteAIVideoProvider("hailuo", "HAILUO_API_KEY"),
        "ltx": LocalLTXFallbackProvider(),
    }
    if name in providers:
        return providers[name]
    priority = [item.strip().lower() for item in os.getenv("AI_VIDEO_PROVIDER_PRIORITY", "veo,kling,runway,pixverse,hailuo").split(",") if item.strip()]
    for candidate in priority:
        provider = providers.get(candidate)
        if provider and provider.available():
            return provider
    return OffAIVideoProvider()


def _missing_provider_warning(provider_name: str) -> str:
    if provider_name == "off":
        return "AI_VIDEO_PROVIDER is off; AI scene videos were not generated. Image render fallback may still run."
    return f"{provider_name} AI video provider is not configured or not implemented; scene videos were not generated."


def _write_result(video_dir: Path, result: dict) -> dict:
    result = {"generated_at": datetime.now(timezone.utc).isoformat(), **result}
    (video_dir / "ai-video-result.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    return result


def _read_json(path: Path) -> dict | list:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}
