SAMPLE_TRENDS = [
    {
        "title": "AI video agents can edit short clips from one prompt",
        "category": "AI",
        "sources": ["youtube_trends", "google_trends"],
        "published_at": "2026-06-09T09:00:00Z",
        "youtube_views": 2_400_000,
        "youtube_likes": 180_000,
        "google_traffic": 200_000,
        "youtube_search_results": 34,
        "urls": ["https://example.com/ai-video-agents"],
        "evidence": ["Sample: high YouTube views", "Sample: Google Trends breakout"],
    },
    {
        "title": "Late game basketball comeback shocks fans",
        "category": "Sports",
        "sources": ["youtube_trends", "reddit"],
        "published_at": "2026-06-09T07:30:00Z",
        "youtube_views": 1_900_000,
        "youtube_likes": 95_000,
        "reddit_ups": 42_000,
        "youtube_search_results": 48,
        "urls": ["https://example.com/basketball-comeback"],
        "evidence": ["Sample: Reddit discussion spike"],
    },
    {
        "title": "Indie horror story about a doorbell camera goes viral",
        "category": "Horror Stories",
        "sources": ["youtube_search", "reddit"],
        "published_at": "2026-06-09T04:45:00Z",
        "youtube_views": 880_000,
        "youtube_likes": 76_000,
        "reddit_ups": 31_000,
        "youtube_search_results": 22,
        "urls": ["https://example.com/doorbell-horror"],
        "evidence": ["Sample: low competition horror angle"],
    },
    {
        "title": "Funny kid explains homework with accidental genius logic",
        "category": "Funny Kids",
        "sources": ["youtube_trends"],
        "published_at": "2026-06-09T11:00:00Z",
        "youtube_views": 1_100_000,
        "youtube_likes": 82_000,
        "youtube_search_results": 18,
        "urls": ["https://example.com/funny-kid-homework"],
        "evidence": ["Sample: short-form friendly topic"],
    },
    {
        "title": "Major game update changes the fastest strategy",
        "category": "Gaming",
        "sources": ["youtube_search", "reddit"],
        "published_at": "2026-06-08T21:00:00Z",
        "youtube_views": 1_600_000,
        "youtube_likes": 110_000,
        "reddit_ups": 24_000,
        "youtube_search_results": 57,
        "urls": ["https://example.com/game-update"],
        "evidence": ["Sample: high gaming velocity"],
    },
    {
        "title": "Celebrity red carpet reaction becomes a meme",
        "category": "Celebrity",
        "sources": ["google_trends", "youtube_search"],
        "published_at": "2026-06-09T02:00:00Z",
        "youtube_views": 1_300_000,
        "youtube_likes": 70_000,
        "google_traffic": 100_000,
        "youtube_search_results": 66,
        "urls": ["https://example.com/red-carpet-reaction"],
        "evidence": ["Sample: broad meme potential"],
    },
    {
        "title": "Rescue dog learns a new trick in one minute",
        "category": "Animals",
        "sources": ["youtube_trends", "reddit"],
        "published_at": "2026-06-09T10:15:00Z",
        "youtube_views": 980_000,
        "youtube_likes": 88_000,
        "reddit_ups": 19_000,
        "youtube_search_results": 16,
        "urls": ["https://example.com/rescue-dog-trick"],
        "evidence": ["Sample: emotional animal story"],
    },
    {
        "title": "Streaming series finale theory divides viewers",
        "category": "Movies & TV",
        "sources": ["google_trends", "reddit"],
        "published_at": "2026-06-08T23:40:00Z",
        "google_traffic": 150_000,
        "reddit_ups": 27_000,
        "youtube_search_results": 41,
        "urls": ["https://example.com/finale-theory"],
        "evidence": ["Sample: debate-driven topic"],
    },
    {
        "title": "Viral news clip sparks debate about airport robots",
        "category": "Viral News",
        "sources": ["youtube_trends", "google_trends"],
        "published_at": "2026-06-09T05:20:00Z",
        "youtube_views": 1_500_000,
        "youtube_likes": 64_000,
        "google_traffic": 120_000,
        "youtube_search_results": 52,
        "urls": ["https://example.com/airport-robots"],
        "evidence": ["Sample: news and AI overlap"],
    },
    {
        "title": "Tiny kitchen cleaning hack spreads across Shorts",
        "category": "Misc Viral",
        "sources": ["youtube_search", "google_trends"],
        "published_at": "2026-06-09T08:10:00Z",
        "youtube_views": 760_000,
        "youtube_likes": 48_000,
        "google_traffic": 80_000,
        "youtube_search_results": 24,
        "urls": ["https://example.com/kitchen-cleaning-hack"],
        "evidence": ["Sample: practical viral hook"],
    },
    {
        "title": "AI voice prank format starts trending again",
        "category": "AI",
        "sources": ["youtube_search", "reddit"],
        "published_at": "2026-06-08T20:00:00Z",
        "youtube_views": 690_000,
        "youtube_likes": 40_000,
        "reddit_ups": 12_000,
        "youtube_search_results": 39,
        "urls": ["https://example.com/ai-voice-prank"],
        "evidence": ["Sample: repeatable format"],
    },
]
