SAMPLE_TRENDS = [
    {
        "title": "Cat knocks over cup then blames the dog",
        "category": "Funny Animals",
        "sources": ["youtube_trends", "reddit"],
        "published_at": "2026-06-12T08:00:00Z",
        "youtube_views": 2_800_000,
        "youtube_likes": 240_000,
        "reddit_ups": 38_000,
        "youtube_search_results": 18,
        "evidence": ["High pet reaction replay value"],
    },
    {
        "title": "Kid gives the most confident wrong answer in class",
        "category": "Funny Kids",
        "sources": ["youtube_trends"],
        "published_at": "2026-06-12T07:20:00Z",
        "youtube_views": 1_900_000,
        "youtube_likes": 160_000,
        "youtube_search_results": 16,
        "evidence": ["Short payoff and family-safe comedy"],
    },
    {
        "title": "Door camera catches knocking with nobody outside",
        "category": "Horror Stories",
        "sources": ["youtube_search", "reddit"],
        "published_at": "2026-06-12T04:40:00Z",
        "youtube_views": 1_100_000,
        "youtube_likes": 94_000,
        "reddit_ups": 44_000,
        "youtube_search_results": 21,
        "evidence": ["Strong curiosity gap"],
    },
    {
        "title": "Team down by 30 makes impossible comeback",
        "category": "Sports Drama",
        "sources": ["youtube_trends", "reddit"],
        "published_at": "2026-06-12T03:15:00Z",
        "youtube_views": 2_100_000,
        "youtube_likes": 130_000,
        "reddit_ups": 52_000,
        "youtube_search_results": 34,
        "evidence": ["High emotional payoff"],
    },
    {
        "title": "Girlfriend finds one hidden text before dinner",
        "category": "Relationship Stories",
        "sources": ["reddit", "youtube_search"],
        "published_at": "2026-06-12T09:10:00Z",
        "youtube_views": 980_000,
        "youtube_likes": 72_000,
        "reddit_ups": 61_000,
        "youtube_search_results": 25,
        "evidence": ["Comment-heavy relationship format"],
    },
    {
        "title": "Minecraft player hears cave noise under his base",
        "category": "Minecraft Stories",
        "sources": ["youtube_search", "reddit"],
        "published_at": "2026-06-12T06:00:00Z",
        "youtube_views": 1_700_000,
        "youtube_likes": 120_000,
        "reddit_ups": 29_000,
        "youtube_search_results": 42,
        "evidence": ["Gaming story with suspense"],
    },
    {
        "title": "Hiker follows wrong footprints and survives",
        "category": "Survival Stories",
        "sources": ["youtube_trends", "google_trends"],
        "published_at": "2026-06-12T05:30:00Z",
        "youtube_views": 1_300_000,
        "youtube_likes": 88_000,
        "google_traffic": 160_000,
        "youtube_search_results": 20,
        "evidence": ["Survival tension and payoff"],
    },
    {
        "title": "Fact about frozen animals sounds impossible",
        "category": "Crazy Facts",
        "sources": ["youtube_search", "google_trends"],
        "published_at": "2026-06-12T10:00:00Z",
        "youtube_views": 1_200_000,
        "youtube_likes": 90_000,
        "google_traffic": 110_000,
        "youtube_search_results": 19,
        "evidence": ["Rewatchable fact reveal"],
    },
]
